// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://calypwrxhicvhznfabyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhbHlwd3J4aGljdmh6bmZhYnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDc5ODYsImV4cCI6MjA1NzE4Mzk4Nn0.v-zIpocyGVRcCO0LGK9HNr21HYDsT9pXksAxYW1waOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);