// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmkbuwbvhubqkuudwrqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZta2J1d2J2aHVicWt1dWR3cnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjU5MjcsImV4cCI6MjA1NzIwMTkyN30.z2kS1Noe_xs51ZF7XOzqyG0VTzxiMrxZ6jtG5209uMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);